version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DOCKER_ENV=true
      - MONGO_URL=mongodb://container-mongo:27017/dbvault
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:4.4
    container_name: container-mongo  
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
