# Użycie obrazu Nginx do serwowania statycznych plików
FROM nginx:latest

# Skopiowanie pliku nginx.conf do katalogu Nginx w kontenerze
COPY ./nginx.conf /etc/nginx/nginx.conf

# Skopiowanie pliku mime.types do katalogu Nginx
COPY ./mime.types /etc/nginx/mime.types

# Skopiowanie plików aplikacji (np. HTML, service worker, manifest, CSS, JS) do katalogu Nginx
COPY . /usr/share/nginx/html

# Ustawienie odpowiednich uprawnień dla plików w katalogu
RUN chmod -R 755 /usr/share/nginx/html && \
    chmod 644 /usr/share/nginx/html/*

# Eksponowanie portu dla Nginx
EXPOSE 80

# Start serwera Nginx
CMD ["nginx", "-g", "daemon off;"]
